# Generated by Django 5.1.5 on 2025-02-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_hire_date_product_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="date",
            new_name="Product_date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discription",
            new_name="Product_discription",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="image",
            new_name="Product_image",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="Product_name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="Product_price",
        ),
    ]
